[
   Constructor,
   NoInterfaceObject,
]
interface Matrix4B : public threeBlinkWrapper {
    void set(float n11, float n12, float n13, float n14, float n21, float n22, float n23, float n24, float n31, float n32, float n33, float n34, float n41, float n42, float n43, float n44);
    void identity();
    void clone();
    Matrix4B* copy();
    Matrix4B* copyPosistion();
    Matrix4B* extractBasis();
    Matrix4B* makeBasis();
    Matrix4B* extractRotation();
    Matrix4B* makeRotationFromEuler(EulerB* euler);
};
